### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by nelreina** [supnate/rekit#2] opened 2016-08-14 02:58 UTC
I get the following error when trying to use rekit.
running on MACOS 
`$ rekit app-name`

**Comment by supnate** [comment] 2016-08-14 04:37
Thanks @nelreina for reporting the issue.
It's caused by crlf line ending checked in by windows system. Now fixed. Please run `npm update rekit -g` to fix. Sorry for the inconvenience.

**Closed by supnate** 2016-08-14 04:37 UTC

**Comment by nelreina** [comment] 2016-08-14 08:21
YEP 👍  It works! Tnxs for the quick fix!
