### ISSUE TITLE
route is error in Chrome (chrome version is the latest)

### ISSUE THREAD

**Issue by samandachen** [supnate/rekit#27] opened 2017-06-27 05:45 UTC
i try the example app in chrome, i click the left navigation, the page does not change,but it runs well in Firefox. the rekit protal is also error, the page cannot open.
the error infomation is 'Cannot assign to read only property 'getDisplayName' of object '#<Object>''.

**Comment by supnate** [comment] 2017-06-27 07:29
I can't reproduce the issue. Do you mean there is error when access http://rekit-portal.herokuapp.com using Chrome ?

**Comment by samandachen** [comment] 2017-06-28 03:39
yes, react-route is also error using Chrome. The Chrome version is  59.0.3071.109

**Comment by supnate** [comment] 2017-06-28 03:43
Got it. But I still can't reproduce, anyone who has the same issue could leave a comment here.

**Comment by supnate** [comment] 2017-07-07 05:55
Close it since not reproducible.

**Closed by supnate** 2017-07-07 05:55 UTC
